[package]
name = "tablix-project"
version = "0.1.0"
edition = "2024"

[dependencies]
trash = "3"
anyhow.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

tablix-storage.workspace = true
